### ISSUE TITLE
Когда релиз 1.3 ? Сильно ли будет отличаться от 1.2 ?

### ISSUE THREAD

**Issue by arsensaliev** [moysklad/api-remap-1.3-doc#102]
Если скоро сделают релиз API 1.3 то имеет ли смысл начинать писать интеграцию  на 1.2 ?

**Comment by SergeyTru** [comment]
В ближайшее время выпуск 1.3 не планируется. Версия неанонсированная и может сильно поменяться.
Отличия 1.3 от 1.2 фиксируются в https://github.com/moysklad/api-remap-1.3-doc/blob/master/source/includes/changelog/_changelog.md

**Comment by arsensaliev** [comment]
> В ближайшее время выпуск 1.3 не планируется. Версия неанонсированная и может сильно поменяться.
> Отличия 1.3 от 1.2 фиксируются в https://github.com/moysklad/api-remap-1.3-doc/blob/master/source/includes/changelog/_changelog.md

Спасибо!
